@OrderService.Api_HostAddress = http://localhost:5117

# GET {{OrderService.Api_HostAddress}}/api/Order/Order/{00B349A7-C57A-49BA-ABB3-1F21DC6F5E6D}
# Accept: application/json

POST {{OrderService.Api_HostAddress}}/api/Order/Order
Accept: application/json
Content-Type: application/json
{
  "OrderId": "{CE2AE35B-38E2-4608-8AD0-786B279BFE1E}",
  "PaymentId": "",
  "Street":"555 Antoi Trl",
  "ZipCode" :"75001",
  "City":"Paris",
  "Locality":"France",
  "PhoneNumber":"1234567890",
  "UserId":"1",
  "OrderItems":[
    {
      "ItemId":"1",
      "OrderId":"{CE2AE35B-38E2-4608-8AD0-786B279BFE1E}",
      "UnitPrice":1099.99,
      "Quantity":1
    },
    {
      "ItemId":"2",
      "OrderId":"{CE2AE35B-38E2-4608-8AD0-786B279BFE1E}",
      "UnitPrice":399.99,
      "Quantity":1
    }
  ]
}

###
